### ISSUE TITLE
typo in recovered cases card

### ISSUE THREAD

**Issue by thoughtlessmind** [Aman22sharma/covid_19_tracker_app#3]
![image](https://user-images.githubusercontent.com/51883613/79103380-1042e600-7d8a-11ea-89d7-0afc8ce8bc73.png)
it should be recovered patients instead of active cases.

**Comment by Aman22sharma** [comment]
yes i saw this silly mistake i will update it

**Comment by Aman22sharma** [comment]
thanks for correcting this
